defaults:
  - hpo_config: template
  - training_config: resnet18_baseline_cifar10
  - quantization_config: quantize_kmeans
  - perturb_regularization_config: template

study_name: resnet18_baseline_cifar10
seed: 1
reruns: 0
epochs_test: -1
