defaults:
  - hpo_config: template
  - training_config: load_config
  - quantization_config: quantize_kmeans
  - perturb_regularization_config: perturb_resnet18

study_name: resnet18_baseline
seed: 1
reruns: 0
epochs_test: -1
load_checkpoint: /run/media/dima/Scratch/perturb_experiment/run_out/resnet18_perturb_loss_01_experiment/15/checkpoints/0/64.pth
